---
# handlers file for webserver

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: yes

- name: Restart webapp
  ansible.builtin.systemd:
    name: '{{ app_name }}'
    state: restarted