---
# tasks file for common
- name: Ensure apt cache is up to date
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Ensure common packages are installed
  ansible.builtin.apt:
    state: present
    name: '{{ apt_packages }}'